import Header from '@/components/shared/Header';
import ThemeLayout from '@/components/shared/ThemeLayout';
import { ClerkProvider } from '@clerk/nextjs';
import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ThemeProviderTailwind from '@/context/TailwindThemeContext';
import Leftbar from '@/components/shared/Leftbar';
import GlobalProvider from '@/context/GlobalProvider';
import MobileNav from '@/components/shared/MobileNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <GlobalProvider>
            <ThemeLayout>
              <Header />
              <main className="flex">
                <Leftbar />
                {children}
              </main>
              <MobileNav />
            </ThemeLayout>
          </GlobalProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
